if game.PlaceId == 126509999114328 then --- 99 Night
loadstring(game:HttpGet("https://raw.githubusercontent.com/ElonMusk136/bypass-Script/refs/heads/main/xiaoyue/99%20Night.txt"))()
elseif game.PlaceId == 2753915549 then --- Blox Fruits
loadstring(game:HttpGet("https://raw.githubusercontent.com/ElonMusk136/bypass-Script/refs/heads/main/xiaoyue/Blox%20Fruit.txt"))()
elseif game.PlaceId == 18687417158 then --- Forsaken
loadstring(game:HttpGet("https://raw.githubusercontent.com/ElonMusk136/bypass-Script/refs/heads/main/xiaoyue/Forsaken.txt"))()
else
game:GetService("Players").LocalPlayer:Kick("UnSupport Game")
end
